### PR TITLE
Fix notification about directories renaming

### LINKED ISSUE #24: Rename event notification does not take into account directory changes
### Expected Behavior
When you have a structure like /dir/file1 /dir/file2 you can do a rename of the directory like rename dir dir2, so the files end up in /dir2/file1 /dir2/file1 . I expected a rename notification of the dir change as it affects the path of the files.

### Current Behavior
No notification of the dir renaming.

### Possible Solution
Send a notification when the dir renaming happens.

### Steps to Reproduce

1. create dir, create a file inside it
2. rename the dir

### PR DESCRIPTION
**Pull request by dtitov**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Now Mina inbox also captures events of renaming/moving of directories, and published corresponding messages.

### Related issues:
Fixes https://github.com/NBISweden/LocalEGA-inbox/issues/24

### CODE REVIEW

File: src/test/java/se/nbis/lega/inbox/sftp/InboxSftpEventListenerTest.java [hunk 1]
```diff
@@ -122,6 +125,31 @@ public void renameFile() throws IOException {
...
+        fileBlockingQueue.poll();
+
+        sftpClient.rename("test/test1", "test/test2");
+
+        FileDescriptor fileDescriptor = fileBlockingQueue.poll();
+        assertNotNull(fileDescriptor);
+        assertEquals(username, fileDescriptor.getUser());
+        String expectedOldPath = inboxFolder + "/" + username + "/test/test1";
+        String expectedPath = inboxFolder + "/" + username + "/test/test2";
+        assertTrue(new File(expectedPath).exists());
```
Comment (amgadhanafy) [inline src/test/java/se/nbis/lega/inbox/sftp/InboxSftpEventListenerTest.java:140]: Use Junit rule `ErrorCollector` 
https://carminetech.wordpress.com/2015/10/30/junit-how-to-collect-multiple-assertion-results-in-one-test/

File: src/test/java/se/nbis/lega/inbox/sftp/S3SftpEventListenerTest.java [hunk 2]
```diff
@@ -124,6 +124,52 @@ public void renameFile() throws IOException {
...
+        sftpClient.mkdir("test/test1");
+
+        sftpClient.put(file.getAbsolutePath(), "test/test1/" + file.getName());
+        fileBlockingQueue.poll();
+
+        sftpClient.rename("test", "test2");
+
+        FileDescriptor fileDescriptor = fileBlockingQueue.poll();
+        assertNotNull(fileDescriptor);
+        assertEquals(username, fileDescriptor.getUser());
```
Comment (amgadhanafy) [inline src/test/java/se/nbis/lega/inbox/sftp/S3SftpEventListenerTest.java:139]: Use Junit rule `ErrorCollector` 
https://carminetech.wordpress.com/2015/10/30/junit-how-to-collect-multiple-assertion-results-in-one-test/

**Review by amgadhanafy — CHANGES_REQUESTED** [review]

**Review by amgadhanafy — APPROVED** [review]
